const users = [
  {
    id: 1,
    name: { firstName: "John", lastName: "Doe" },
    email: "johndoe@example.com",
    company: { name: "ACME Corp" },
    experience: 5,
    isActive: true,
    department: "Engineering",
  },
  {
    id: 2,
    name: { firstName: "Jane", lastName: "Smith" },
    email: "janesmith@example.com",
    company: null,
    experience: 3,
    isActive: false,
    department: "Sales",
  },
  {
    id: 3,
    name: null,
    email: "invalid@email",
    company: { name: "MegaCorp" },
    experience: 0,
    isActive: undefined,
    department: "Customer Success",
  },
  {
    id: 4,
    name: { firstName: "Alice" },
    email: "alice@work.com",
    company: null,
    experience: 7,
    isActive: true,
    department: "engineering",
  },
  {
    id: 5,
    name: { lastName: "Johnson" },
    email: null,
    company: { name: "Global Inc" },
    experience: 2,
    isActive: false,
    department: "SALES",
  },
  {
    id: 6,
    name: null,
    email: "johndoe2@example.com",
    company: null,
    experience: null,
    isActive: true,
    department: null,
  },
  {
    id: 7,
    name: { firstName: "Michael" },
    email: "michael@company.com",
    company: { name: "Tech Solutions" },
    experience: 10,
    isActive: undefined,
    department: "customerSuccess",
  },
  {
    id: 8,
    name: null,
    email: null,
    company: null,
    experience: 0,
    isActive: false,
    department: "QA",
  },
  {
    id: 9,
    name: { firstName: "Emily", lastName: "Wang" },
    email: "emily.wang@workplace.org",
    company: null,
    experience: 4,
    isActive: true,
    department: "Engineering",
  },
  {
    id: 10,
    name: null,
    email: "invalid@email2",
    company: { name: "StartUp Inc" },
    experience: null,
    isActive: null,
    department: null,
  },
  {
    id: 11,
    name: { firstName: "David", lastName: "Lee" },
    email: "david.lee@company.com",
    company: null,
    experience: 8,
    isActive: false,
    department: "Sales",
  },
  {
    id: 12,
    name: { firstName: "Sarah" },
    email: "sarah@work.net",
    company: { name: "Tech Solutions" },
    experience: 2,
    isActive: true,
    department: "QA",
  },
  {
    id: 13,
    name: null,
    email: null,
    company: null,
    experience: 0,
    isActive: true,
    department: null,
  },
  {
    id: 14,
    name: { firstName: "William", lastName: "Brown" },
    email: "william.brown@workplace.org",
    company: { name: "Global Inc" },
    experience: 6,
    isActive: false,
    department: "customer success",
  },
  {
    id: 15,
    name: null,
    email: "invalid@email3",
    company: null,
    experience: null,
    isActive: undefined,
    department: "SALES",
  },
 ];
 
 const products = [
  {
      name: "Laptop",
      weight: "1.5 kg",
      category: "Electronics",
      price: 1200
  },
  {
      name: "Smartphone",
      weight: "0.2 kg",
      category: "Electronics",
      price: 800
  },
  {
      name: "Headphones",
      weight: "0.1 kg",
      category: "Electronics",
      price: 150
  },
  {
      name: "Running Shoes",
      weight: "0.8 kg",
      category: "Sporting Goods",
      price: 80
  },
 ]

 export {users,products} 